builds:
  - binary: go-cli-app
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: go-cli-app
    homepage: https://github.com/rmpalgo/go-cli-app

checksum:
  name_template: 'checksums.txt'